### ISSUE TITLE
No sound while i got new notifications

### ISSUE THREAD

**Issue by Mark-papi** [basknol/MMM-PushBulletNotifications#14]
How can i enable the sound when i get a notification?
cause it is true but i dont here sound.
I even do it as an absolute path, but i dont get the sound.

ohhhh forgot the package...

**Comment by Mark-papi** [comment]
still the sound is not playing after i npm

**Comment by basknol** [comment]
Hi @Mark-papi,

The module uses omxplayer to play the sound, these configuration options are needed to play a sound:   

- `playSoundOnNotificationReceived: true,`
- `soundFile: 'modules/MMM-PushBulletNotifications/sounds/new-message.mp3', //Relative path to MagicMirror root`

Are you using a Raspberry pi for the Magic Mirror?
Is there a folder 'sounds' in de MMM-PushBulletNotifications module folder?
Did you look in the logging for clues or try to start the Magic Mirror with `npm start dev`? Are there any errors?

**Comment by Mark-papi** [comment]
Thank you!
i will check it out again and i will respond shortly
im using rpi
there is a folder sounds.

**Comment by Mark-papi** [comment]
![2018-12-25 3](https://user-images.githubusercontent.com/12816482/50419639-71b01000-083a-11e9-9749-924c2e282163.png)

**Comment by Mark-papi** [comment]
the problem still persists for some reason, do i forget something?

**Comment by basknol** [comment]
Thanks for your response! 

Did you also check the logging when starting the Magic Mirror from the command line with `npm start dev`? Any errors?

Can you play a sound from your rpi at all? Do you use HDMI or headphone jack as audio output?
Do you hear anything if you navigate to the sounds folder and use the command `omxplayer new-message.mp3`?

You can try to force the audio over HDMI or 3.5 mm (headphone) jack using: raspi-config -> Advanced Options -> Audio.
Or set the output using the volume control on the desktop taskbar.
Please see: [Raspbery Pi audio configuration](https://www.raspberrypi.org/documentation/configuration/audio-config.md)

Hope this helps!

**Comment by Mark-papi** [comment]
The sound is playing when I try to open it while GUI, but I will try to run it with omxplayer in CLI to be sure.
I will respond shortly,  thank you for helping me :)

**Comment by Mark-papi** [comment]
I run it and I got that,but without sound, https://imgur.com/a/XNJjCt3

**Comment by Mark-papi** [comment]
By changing the command to omxplayer -o alsa new-message.mp3 
Is playing,  but how could I do it, in the module?
What file should I alert to add the alsa inside.?

**Comment by Mark-papi** [comment]
I fixed it, I used aplay in the array players on helper-node.js
And used a wav file and is playing nice.
Thank you for your module ;)
Now something else, if I want to make it make different sounds for different notification,  how I could do that? 

Example given,  I get a Facebook notification,  so I want to have a Facebook message sound, I get a viber notification so I want to have a viber sound.

**Comment by basknol** [comment]
Hi @Mark-papi,

Good to hear you fixed it using aplay as one of the players.

If have created a new branch [feature_audio](https://github.com/basknol/MMM-PushBulletNotifications/tree/feature_audio). This branch contains functionality to play a different sound based on the mirrored notification application. It uses the property 'application_name' that is sent by PushBullet for the mirrored notifications.

I don't know what all the applications names are, but you can track them down by setting the debugMode configuration option for the MMM-PushBulletNotifications module to true.
<code>debugMode: true</code> 

In the logging or when starting the Magic Mirror with `npm start dev` you can see all the received JSON messages from PushBullet en see what 'application_name' values are used. You could also try guessing them, the application name for Facebook will most likely be 'facebook'.

The application name (lower case value, for example 'whatsapp') is used to search for a corresponding filename (regardless of extension) in the configured sounds directory (see configurations options). The sound wille be played if a corresponding filename is found. So place a 'whatsapp.mp3' and 'facebook.mp3' in the (configured) sounds directory and see if a different sound is played.

Please try the [feature_audio](https://github.com/basknol/MMM-PushBulletNotifications/tree/feature_audio) branch and give me some feedback if this works correctly.

I have also added an option 'audioPlayer' in this branch, so you can configure different audio players (like 'aplay') instead of changing the code in node_helper.js.

Hope to hear from you!
