### ISSUE TITLE
Notifications doesn't disappear

### ISSUE THREAD

**Issue by JcbSndstrm** [basknol/MMM-PushBulletNotifications#4]
Sometimes notifications does not disappear. I have noticed it from messenger and whatsapp. If its not possible to resolve the issue I would like an option to hide notifications after a set time.

**Comment by basknol** [comment]
Hi @JcbSndstrm,

This could be the same issue as mentioned here: [https://github.com/basknol/MMM-PushBulletNotifications/issues/5#issue-367534138](5)

Please see my comment in there.

Are you also using pushes or mirror notifications only?
I was not able to reproduce this error. I will first try to fix this issue, if this is not possible due to a limitation or bug in the PushBullet API I will see if I can implement a feature that will hide notifications after a configurable period of time. Thanks for the suggestion!

**Comment by basknol** [comment]
Same issue as #5. See comments in issue #5, bug is solved!
